apiVersion: v1
kind: Pod
metadata:
  name: abs-hello-csharp-app
  labels:
    app: abs-hello-csharp-app
spec:
  containers:
  - image: "abhinabsarkar/abs-hello-csharp:v1"
    name: abs-hello-csharp-app-image
    ports:
    - containerPort: 80
      protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: abs-hello-csharp-app
spec:
  selector:
    app: abs-hello-csharp-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: abs-hello-csharp-app
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - path: /abs
        backend:
          serviceName: abs-hello-csharp-app
          servicePort: 80
